postgres:
  build: ./postgres
  ports:
   - "5432:5432"
  volumes:
   - ./postgres/data:/var/lib/postgresql/data
  env_file:
   - ./conf.env

#web:
#  build: ./server
#  links:
#   - postgres
#  volumes:
#   - ../server:/lindoria
#  command: npm start
#  env_file:
#   - ./conf.env