export const SET_LANDING_FOCUS = 'SET_LANDING_FOCUS';
export const GET_CONTENT = 'GET_CONTENT';
export const BR_DATA = 'BR_DATA';
export const TOGGLE_CREATE_MENU = 'TOGGLE_CREATE_MENU';
export const LOAD_EDIT_FOCUS = 'LOAD_EDIT_FOCUS';
export const REMOVE_EDIT_FOCUS = 'REMOVE_EDIT_FOCUS';